FROM node:18

RUN apt-get update && apt-get install -y \
    yarn

WORKDIR '/app'
COPY package.json ./
COPY . .
RUN yarn

# next two line are needed t get ownership of the node_modules
# RUN chown node:node /app/node_modules
# USER node


CMD ["yarn",  "dev"]