version: "3"

networks: 
  wordpress_nginx:
    driver: bridge

services:
  ### MYSQL
  mysql:
    image: mysql:latest
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - wordpress_nginx

  ### WORDPRESS
  wordpress:
    depends_on: 
      - mysql
    image: wordpress:5.7.2-fpm-alpine
    restart: always
    volumes: 
      - ./wp:/var/www/html
    env_file: .env
    environment: 
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    networks: 
      - wordpress_nginx

  ### NGINX
  nginx:
    depends_on: 
      - wordpress
    image: nginx:stable-alpine
    ports: 
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wp:/var/www/html
    networks: 
      - wordpress_nginx

  ### PHPMYADMIN
  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - mysql:db
    env_file: .env
    ports: 
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks: 
      - wordpress_nginx