version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - mongodb
    env_file:
      - ./env/mongodb.env

networks:
  mongodb:
    driver: bridge