services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - mongodb
    env_file:
      - ./env/mongodb.env

  backend:

networks:
  mongodb:
    driver: bridge

volumes:
  data:
    driver: local
