version: '3'

###### NETWORKS
networks: 
  wp_site:

###### VOLUMES
volumes: 
  db_data:

services:
  # database
  mysql_db:
    image: mysql:latest
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    networks: 
      - wp_site

  #phpmyadmin
  phpmyadmin:
    depends_on: 
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - mysql_db:db
    ports: 
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - wp_site

  # wordpress
  wordpress:
    depends_on: 
      - mysql_db
    image: wordpress:latest
    ports: 
      - 8000:80
    restart: always
    volumes: ['./wp:/var/www/html']
    environment: 
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
    networks: 
      - wp_site