version: '3'

services:
  redis-server:
    image: redis
  node-app:
    restart: always
    build: .
    ports:
      - '4001:8081' # first is the port on you local-machine and the second is the port inside the container