---
services:
  npm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-utility-container
    image: nodejs-utility-container:cliuser
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
