---
networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  # ---------------------------------------------------------------------
  # | Nginx - Web Server                                                |
  # ---------------------------------------------------------------------
  nginx-web-server:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      # :ro - read only | :rw - read write
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
  # ---------------------------------------------------------------------
  # | PHP - Web Service                                                 |
  # ---------------------------------------------------------------------
  php-web-service:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      # :delegated - sync files between host and container
      - ./src:/var/www/html:delegated
    networks:
      - default
  # ---------------------------------------------------------------------
  # | MySQL - Database                                                  |
  # ---------------------------------------------------------------------
  mysql-database:
    image: mysql:5.7
    container_name: mysql-database
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    networks:
      - default
  # ---------------------------------------------------------------------
  # | Composer - Utility Container                                      |
  # ---------------------------------------------------------------------
  composer-utility-container:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      # :delegated - sync files between host and container
      - ./src:/var/www/html:delegated
    networks:
      - default
  # npm-utility:
  # artisan-utility:
