---
networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  # ---------------------------------------------------------------------
  # | Nginx - Web Server                                                |
  # ---------------------------------------------------------------------
  nginx-web-server:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      # :ro - read only | :rw - read write
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:delegated
    networks:
      - default
    depends_on:
      - php-web-service
      - mysql-database

  # ---------------------------------------------------------------------
  # | PHP - Web Service                                                 |
  # ---------------------------------------------------------------------
  php-web-service:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      # :delegated - sync files between host and container
      - ./src:/var/www/html:delegated
    networks:
      - default
    depends_on:
      - mysql-database

  # ---------------------------------------------------------------------
  # | MySQL - Database                                                  |
  # ---------------------------------------------------------------------
  mysql-database:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql-database
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    networks:
      - default

  # ---------------------------------------------------------------------
  # | Composer - Utility Container                                      |
  # ---------------------------------------------------------------------
  composer-utility-container:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      # :delegated - sync files between host and container
      - ./src:/var/www/html:delegated
    networks:
      - default

  # ---------------------------------------------------------------------
  # | Artisan - Utility Container                                       |
  # ---------------------------------------------------------------------
  artisan-utility-container:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      # :delegated - sync files between host and container
      - ./src:/var/www/html:delegated
    networks:
      - default
    entrypoint: ["php", "/var/www/html/artisan"]

  # ---------------------------------------------------------------------
  # | NPM - Utility Container                                           |
  # ---------------------------------------------------------------------
  npm-utility-container:
    image: node:20
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html:delegated
